name: Deploy to GitHub Pages
on:
 push:
 branches: ["main"] # or "master" if that's your default branch
permissions:
 pages: write
 id-token: write
jobs:
 deploy:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout code
 uses: actions/checkout@v4
 - name: Setup Pages
 uses: actions/configure-pages@v4
 - name: Upload artifact
 uses: actions/upload-pages-artifact@v3
 with:
 # Upload the entire repository (or specify just your web files)
 path: './'
 - name: Deploy to GitHub Pages
 uses: actions/deploy-pages@v4
